# Generated by Django 5.1.7 on 2025-05-14 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vaga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('area', models.CharField(choices=[('adm', 'Administração'), ('eng', 'Engenharia'), ('tec', 'Tecnologia da Informação'), ('edu', 'Educação'), ('jur', 'Direito'), ('med', 'Medicina'), ('enf', 'Enfermagem'), ('fin', 'Finanças'), ('mkt', 'Marketing'), ('com', 'Comércio'), ('arq', 'Arquitetura'), ('des', 'Design'), ('coms', 'Comunicação Social'), ('log', 'Logística'), ('rec', 'Recursos Humanos'), ('tur', 'Turismo'), ('agr', 'Agronomia'), ('vet', 'Medicina Veterinária'), ('art', 'Artes'), ('out', 'Outros')], max_length=50)),
                ('tipo_contrato', models.CharField(choices=[('clt', 'CLT (Efetivo)'), ('pj', 'Pessoa Jurídica (PJ)'), ('est', 'Estágio'), ('tra', 'Temporário'), ('fre', 'Freelancer'), ('apr', 'Aprendiz'), ('aut', 'Autônomo'), ('vol', 'Voluntário'), ('int', 'Intermitente'), ('out', 'Outros')], max_length=50)),
                ('descricao', models.TextField()),
            ],
        ),
    ]
