# Generated by Django 5.1.7 on 2025-05-14 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vagas_e_candidatos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('sobrenome', models.CharField(max_length=100)),
                ('data_nascimento', models.DateField()),
                ('genero', models.CharField(choices=[('mas', 'Masculino'), ('fem', 'Feminino'), ('ninf', 'Prefere não informar')], max_length=10)),
                ('email', models.EmailField(max_length=100)),
                ('telefone', models.CharField(max_length=15)),
                ('escolaridade', models.CharField(choices=[('nin', 'Nenhuma'), ('funi', 'Fundamental Incompleto'), ('fuc', 'Fundamental Completo'), ('mei', 'Médio Incompleto'), ('med', 'Médio Completo'), ('sui', 'Superior Incompleto'), ('sup', 'Superior Completo'), ('pos', 'Pós-graduação'), ('mes', 'Mestrado'), ('dou', 'Doutorado')], max_length=30)),
            ],
        ),
    ]
