# Generated by Django 5.1.7 on 2025-05-14 15:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vagas_e_candidatos', '0002_candidato'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidato',
            name='vaga',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vagas_e_candidatos.vaga'),
        ),
    ]
